import { describe, expect, it, vi } from 'vitest';
import { DishesService } from '../src/modules/dishes';
describe('DishesService', () => {
  it('创建菜品时绑定 kitchenId 和创建者', async () => { const create = vi.fn(); const service = new DishesService({ create } as never); await service.create('kitchen-a', 'user-a', { name: '番茄鸡蛋' }); expect(create).toHaveBeenCalledWith('kitchen-a', 'user-a', expect.objectContaining({ name: '番茄鸡蛋' })); });
  it('点评先按厨房读取菜品再 Upsert', async () => { const get = vi.fn().mockResolvedValue({ id: 'dish-1' }); const review = vi.fn(); const service = new DishesService({ get, review } as never); await service.review('kitchen-a', 'dish-1', 'user-a', { tasteRating: 5, appearanceRating: 4, careRating: 5 }); expect(get).toHaveBeenCalledWith('kitchen-a', 'dish-1'); expect(review).toHaveBeenCalledWith('kitchen-a', 'dish-1', 'user-a', expect.anything()); });
  it('软删除通过 Repository 绑定厨房', async () => { const remove = vi.fn().mockResolvedValue({ count: 1 }); const service = new DishesService({ remove } as never); await service.remove('kitchen-a', 'dish-1'); expect(remove).toHaveBeenCalledWith('kitchen-a', 'dish-1'); });
  it('更新只映射允许字段', async () => { const update = vi.fn().mockResolvedValue({ count: 1 }); const get = vi.fn().mockResolvedValue({ id: 'dish-1' }); const service = new DishesService({ update, get } as never); await service.update('kitchen-a', 'dish-1', { name: '新菜名', kitchenId: 'bad' } as never); expect(update).toHaveBeenCalledWith('kitchen-a', 'dish-1', { name: '新菜名' }); });
  it('拒绝空更新', async () => { const update = vi.fn(); const service = new DishesService({ update } as never); await expect(service.update('kitchen-a', 'dish-1', {})).rejects.toThrow('至少提供一个要更新的字段'); expect(update).not.toHaveBeenCalled(); });
  it('生成稳定 Cursor 页面并拒绝伪造 Cursor', async () => { const rows = [{ id: '10000000-0000-4000-8000-000000000001', createdAt: new Date('2026-01-02') }, { id: '10000000-0000-4000-8000-000000000002', createdAt: new Date('2026-01-01') }]; const service = new DishesService({ listCursor: vi.fn().mockResolvedValue(rows) } as never); const page = await service.listV2('k', 1); expect(page.pageInfo.hasNextPage).toBe(true); expect(page.pageInfo.nextCursor).toEqual(expect.any(String)); await expect(service.listV2('k', 1, 'bad')).rejects.toMatchObject({ response: { code: 'INVALID_CURSOR' } }); });
});
